# 数据库配置文件
# 复制此文件为 config.yaml 并修改相应的配置

# MySQL 配置
mysql:
  host: localhost
  port: 3306
  database: idle_server
  username: root
  password: ""  # 请设置您的MySQL密码
  charset: utf8mb4
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 300  # 秒

# Redis 配置
redis:
  host: localhost
  port: 6379
  password: ""  # 如果有密码请设置
  db: 0
  pool_size: 10
  min_idle_conns: 3

# 应用配置
app:
  log_level: info
  health_check_interval: 30  # 秒
  cache_ttl: 1800  # 秒 (30分钟)

# 开发环境配置
development:
  mysql:
    host: localhost
    port: 3306
    database: idle_server_dev
    username: root
    password: ""
  redis:
    host: localhost
    port: 6379
    db: 1

# 生产环境配置
production:
  mysql:
    host: your-mysql-host
    port: 3306
    database: idle_server
    username: your-app-user
    password: your-secure-password
  redis:
    host: your-redis-host
    port: 6379
    password: your-redis-password
    db: 0